### ISSUE TITLE
Force close with this error

### ISSUE THREAD

**Issue by 3xtazzy** [purpxd/E7AutoShop#10]
Installed the requirements, using Python 3.11

```ERROR:root:cannot identify image file <_io.BytesIO object at 0x000001FEEDE3B8D0>
Traceback (most recent call last):
  File "C:\Games\E7AutoShop\build\shop.py", line 263, in main
    screenshot = self.screen()
                 ^^^^^^^^^^^^^
  File "C:\Games\E7AutoShop\build\shop.py", line 134, in screen
    screenshot = Image.open(BytesIO(img_bytes))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Games\E7AutoShop\virtual_env\Lib\site-packages\PIL\Image.py", line 3298, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x000001FEEDE3B8D0>
ERROR:root:cannot identify image file <_io.BytesIO object at 0x00000120D50E2F20>
Traceback (most recent call last):
  File "C:\Games\E7AutoShop\build\shop.py", line 263, in main
    screenshot = self.screen()
                 ^^^^^^^^^^^^^
  File "C:\Games\E7AutoShop\build\shop.py", line 134, in screen
    screenshot = Image.open(BytesIO(img_bytes))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Games\E7AutoShop\virtual_env\Lib\site-packages\PIL\Image.py", line 3298, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x00000120D50E2F20>
ERROR:root:cannot identify image file <_io.BytesIO object at 0x000002A8AA922610>
Traceback (most recent call last):
  File "C:\Games\E7AutoShop\build\shop.py", line 263, in main
    screenshot = self.screen()
                 ^^^^^^^^^^^^^
  File "C:\Games\E7AutoShop\build\shop.py", line 134, in screen
    screenshot = Image.open(BytesIO(img_bytes))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Games\E7AutoShop\virtual_env\Lib\site-packages\PIL\Image.py", line 3298, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x000002A8AA922610>
```

**Comment by purpxd** [comment]
Hello,

The main issue here is that the program is having trouble detecting your emulator. You can launch the app but once you start a run it will throw this error right? 

Others have solved this issue by reinstalling bluestacks or going with another emulator such as LD.

**Comment by 3xtazzy** [comment]
> Hello,
> 
> The main issue here is that the program is having trouble detecting your emulator. You can launch the app but once you start a run it will throw this error right?
> 
> Others have solved this issue by reinstalling bluestacks or going with another emulator such as LD.

Yes, I can open the app. I will consider doing that

**Comment by 3xtazzy** [comment]
It works now! thanks
