### ISSUE TITLE
autoshop.exe not working

### ISSUE THREAD

**Issue by Wanipi** [purpxd/E7AutoShop#12]
Hi, autoshop.exe is not opening, i already download python, installed the app in c:/users/user/downloads and opening in admin and still not working.

this is the error:

```
Traceback (most recent call last):
File "autoshop.py", line 14, in <module>
File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
File "db\models.py", line 112, in <module>
File "db\models.py", line 80, in identify
File "db\models.py", line 28, in uniqueId
File "db\models.py", line 19, in get_mac_address
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa2 in position 9: invalid start byte
[8800] Failed to execute script 'autoshop' due to unhandled exception!
```

**Comment by purpxd** [comment]
> Hi, autoshop.exe is not opening, i already download python, installed the app in c:/users/user/downloads and opening in admin and still not working.
> 
> this is the error:
> 
> ```
> Traceback (most recent call last):
> File "autoshop.py", line 14, in <module>
> File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
> File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
> File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
> File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
> File "db\models.py", line 112, in <module>
> File "db\models.py", line 80, in identify
> File "db\models.py", line 28, in uniqueId
> File "db\models.py", line 19, in get_mac_address
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa2 in position 9: invalid start byte
> [8800] Failed to execute script 'autoshop' due to unhandled exception!
> ```

Hello, 
Thanks for providing me with the error log. Would you by any chance be using a vpn? I've added an update. Go ahead and uninstall the app and go to the releases page and download the new one

**Comment by Wanipi** [comment]
I'm not using a vpn, don't know if the problem is from the dns of google which im using right now.
I installed the updated one and is working. Thanks
