### ISSUE TITLE
AutoShop crashing within 5 seconds after pressing START

### ISSUE THREAD

**Issue by Tofunim** [purpxd/E7AutoShop#23]
Program just straight up crashes whenever I'm trying to start AutoShop. Not sure what's causing the problem. It was like this when I first installed AutoShop (couple of days ago) and then after a couple tries it suddenly worked well **once** and then never again.

I'm using BlueStacks (Pie 64), but it also crashes on LDPlayer (tried it today). Also tried both admin and no admin as well as different file locations for AutoShop.

Experienced 2 types of crashes so far:

Crash 1:
https://github.com/user-attachments/assets/a8194f27-ed55-4208-9b9c-b014d39f7ad7

Crash 1 (On LDPlayer):
https://github.com/user-attachments/assets/114b533c-d919-403e-9c15-ff841e52cfac
(Crashes both on local and remote connection)

Crash 2:
https://github.com/user-attachments/assets/2442b12d-32f1-42cf-b9e7-2fe60d1cef99

Here's what I get in error:

  File "PIL\Image.py", line 3339, in open
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x0000019B5109A160>
ERROR:root:cannot identify image file <_io.BytesIO object at 0x000002981066A200>
Traceback (most recent call last):
  File "scripts\shop.py", line 218, in main
    screenshot = self.screen()
                 ^^^^^^^^^^^^^
  File "scripts\shop.py", line 108, in screen
    screenshot = Image.open(BytesIO(img_bytes))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by purpxd** [comment]
Hey thanks for sending over the videos. The first one is a strange one a few people have experienced and was usually solved by switching to LD. The resolution seems off even though its set properly because the fodder was clicked which would never happen on 1920 res. 

I'd try to update the Bluestacks version to 5.20+ and for the different file locations you tried, have you tested it on different drives? Maybe see if it works in Downloads/Documents on your C drive.

**Comment by Tofunim** [comment]
Thanks for the response and suggestions!

I've updated BlueStacks to the latest version and unfortunately, it still crashes. I also tried it after restarting my PC and still no luck.

For the different file locations, I've tried the Documents on my C drive and a custom folder on my F drive (Internal SSD rigged onto an external case).

One thing that I've noticed is that the **adb.exe** is seen as **Running** even when AutoShop crashes in Task Manager. I was able to notice this when I was trying to reinstall AutoShop by uninstalling it first, but it wouldn't delete the _internal folder due to adb.exe still running in the background. I don't know if adb.exe is supposed to be running in the background like that even without AutoShop running.

Another thing is that I have tried using other auto shop refresh tools that are available on GitHub, mostly the epic7_bot, and that one seemed to work fine (although it is much much slower). It requires adb as well so it does seem like BlueStacks adb is working.

**Comment by purpxd** [comment]
> Thanks for the response and suggestions!
> 
> I've updated BlueStacks to the latest version and unfortunately, it still crashes. I also tried it after restarting my PC and still no luck.
> 
> For the different file locations, I've tried the Documents on my C drive and a custom folder on my F drive (Internal SSD rigged onto an external case).
> 
> One thing that I've noticed is that the **adb.exe** is seen as **Running** even when AutoShop crashes in Task Manager. I was able to notice this when I was trying to reinstall AutoShop by uninstalling it first, but it wouldn't delete the _internal folder due to adb.exe still running in the background. I don't know if adb.exe is supposed to be running in the background like that even without AutoShop running.
> 
> Another thing is that I have tried using other auto shop refresh tools that are available on GitHub, mostly the epic7_bot, and that one seemed to work fine (although it is much much slower). It requires adb as well so it does seem like BlueStacks adb is working.

Great observation there, yeah I should exit adb on app crashes. adb is definitely working for you since it was still clicking the refresh but when we get to the image processing part it fails. 

Let's test if you can generate a screenshot with adb manually. 

1. Go into the _internals directory and locate adb
2. In the adb directory, copy the file path and open up cmd.exe and paste the path in
3. Try executing adb.exe exec-out screencap -p and see if you get an output
4. Try executing adb.exe exec-out screencap -p > screen.png and see if it generates a screenshot

Hopefully this part will fail and you may get an error message that will help us pinpoint the issue

**Comment by Tofunim** [comment]
Alright so I've tried this and got 2 different results.

Result 1 (Seems to be the standard error):
https://github.com/user-attachments/assets/92285648-686c-430c-b2fa-59a168c2dbc3

Result 2 (Looks like something that shouldn't be happening at all):
https://github.com/user-attachments/assets/a2f041ce-d517-429d-a67e-18ee001fb93a

I've tried this multiple times in different ways (AutoShop running, AutoShop not running, turning ADB on and off in BlueStacks while leaving everything else on, etc.) and it seems like Result 2 happens when I make AutoShop crash like in the previous videos and adb.exe is left running in Task Manager. Result 2 will still happen even when I turn on AutoShop again and will only reset back to Result 1 if I close adb.exe through Task Manager or close AutoShop normally without crashing (which also naturally closes adb.exe).

Funnily enough, screenshots are still generated regardless of which result/error I get.

Screenshot after Result 1:
https://github.com/user-attachments/assets/dece64c7-c84e-4e60-864b-ad9ad9c7bed0

Screenshot after Result 2:
https://github.com/user-attachments/assets/c7062099-abd5-48fd-acbc-3d5a29f230a1

**Comment by LarcekGiglamesh** [comment]
i got the same initial report with BlueStack as @Tofunim and also tried a bunch (admin perms, different install folder) but could not get it to work. while installing LD Player the tool mentioned i had some virtualization service running which could affect gaming, so i disabled it once, did an OS restart and gave BlueStacks another try and it works now.

**Comment by saiji929** [comment]
[error.log](https://github.com/user-attachments/files/16614868/error.log)
The application does not start
@purpxd 
a command prompt window appears and immediately closes

**Comment by purpxd** [comment]
> i got the same initial report with BlueStack as @Tofunim and also tried a bunch (admin perms, different install folder) but could not get it to work. while installing LD Player the tool mentioned i had some virtualization service running which could affect gaming, so i disabled it once, did an OS restart and gave BlueStacks another try and it works now. 

That's great! Hopefully this solves tofu's problem and others in the future

**Comment by purpxd** [comment]
> [error.log](https://github.com/user-attachments/files/16614868/error.log)
> 
> The application does not start
> 
> @purpxd 
> 
> a command prompt window appears and immediately closes

There's a problem with your connection. I'll probably have an update to resolve this maybe by the weekend
